class DefaultConfig:
    FILE_JMP_PROBABILITY = 0.1
    NUM_FILE_POINTERS = 8
    SPM_MODEL_TYPE = 'unigram'


class OpenAIConfig:
    VOCAB_SIZE = 40478
    USE_SINGLE_SENTENCE = True
    TRAINABLE_POS_EMBEDDING = True
    EMBEDDING_SIZE = 768
    MAX_LEN = 512
    MIN_LEN = None
    EMBEDDING_DROPOUT = 0.1
    USE_ONE_EMBEDDING_DROPOUT = True
    NUM_LAYERS = 12


class BERTConfig:
    VOCAB_SIZE = 30000
    MAX_LEN = 512
    MIN_LEN = None
    KEEP_PROBABILITY = 0.85
    MASK_PROBABILITY = 0.15 * 0.8
    RAND_PROBABILITY = 0.15 * 0.1
    MISMATCH_PROBABILITY = 0.5
    STEPS = 1000000
    USE_SINGLE_SENTENCE = False
    BATCH_SIZE = 256
    TRAINABLE_POS_EMBEDDING = True
    EMBEDDING_DROPOUT = 0.1
    NUM_SEGMENTS = 2
